[06/ago./2020 19:17:42] ERROR [django.request:256] Internal Server Error: /comprobantes/movimientos/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 146, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: fm/movimientos/modal.html
[06/ago./2020 19:17:49] ERROR [django.request:256] Internal Server Error: /comprobantes/movimientos/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 146, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: fm/movimientos/modal.html
[06/ago./2020 19:18:13] ERROR [django.request:256] Internal Server Error: /comprobantes/movimientos/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'fm_tags' is not a valid tag library: Template library fm_tags not found, tried django.templatetags.fm_tags,django.contrib.staticfiles.templatetags.fm_tags,django.contrib.admin.templatetags.fm_tags,django.contrib.humanize.templatetags.fm_tags,bootstrap3.templatetags.fm_tags,crispy_forms.templatetags.fm_tags,django_extensions.templatetags.fm_tags,modal.templatetags.fm_tags,comprobantes.templatetags.fm_tags
[06/ago./2020 19:19:18] ERROR [django.request:256] Internal Server Error: /comprobantes/movimientos/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'fm_tags' is not a valid tag library: Template library fm_tags not found, tried django.templatetags.fm_tags,django.contrib.staticfiles.templatetags.fm_tags,django.contrib.admin.templatetags.fm_tags,django.contrib.humanize.templatetags.fm_tags,bootstrap3.templatetags.fm_tags,crispy_forms.templatetags.fm_tags,django_extensions.templatetags.fm_tags,modal.templatetags.fm_tags,comprobantes.templatetags.fm_tags
[06/ago./2020 19:20:15] ERROR [django.request:256] Internal Server Error: /comprobantes/movimientos/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 151, in render
    template = context.template.engine.get_template(template)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'modal_tags' is not a valid tag library: Template library modal_tags not found, tried django.templatetags.modal_tags,django.contrib.staticfiles.templatetags.modal_tags,django.contrib.admin.templatetags.modal_tags,django.contrib.humanize.templatetags.modal_tags,bootstrap3.templatetags.modal_tags,crispy_forms.templatetags.modal_tags,django_extensions.templatetags.modal_tags,modal.templatetags.modal_tags,comprobantes.templatetags.modal_tags
[06/Aug/2020 23:10:30] ERROR [django.request:256] Internal Server Error: /reportes/ingresos_egresos/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\reportes\views.py", line 785, in dispatch
    return super(caja_diaria, self).dispatch(*args,**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
[07/Aug/2020 00:09:18] ERROR [django.request:256] Internal Server Error: /reportes/caja_diaria/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 1195, in render
    return func(*resolved_args, **resolved_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\bootstrap3\templatetags\bootstrap3.py", line 438, in bootstrap_field
    return render_field(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\bootstrap3\forms.py", line 62, in render_field
    return renderer_cls(field, **kwargs).render()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\bootstrap3\renderers.py", line 215, in __init__
    'Parameter "field" should contain a valid Django BoundField.')
BootstrapError: Parameter "field" should contain a valid Django BoundField.
[07/Aug/2020 00:13:52] ERROR [django.request:256] Internal Server Error: /reportes/caja_diaria/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\reportes\views.py", line 698, in dispatch
    return super(caja_diaria, self).dispatch(*args,**kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Repo\ironStable\reportes\views.py", line 812, in post
    return self.get(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
  File "D:\Repo\ironStable\reportes\views.py", line 716, in get_context_data
    cpbs = cpb_comprobante_fp.cpbs_activos.filter(cpb_comprobante__empresa=empresa).select_related('cpb_comprobante','cpb_comprobante__cpb_tipo','cta_egreso','cta_ingreso','tipo_forma_pago').order_by('cpb_comprobante__fecha_cpb','id')
AttributeError: type object 'cpb_comprobante_fp' has no attribute 'cpbs_activos'
[11/Aug/2020 21:29:52] ERROR [django.request:256] Internal Server Error: /comprobantes/saldo_inicial/nuevo/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 1195, in render
    return func(*resolved_args, **resolved_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\bootstrap3\templatetags\bootstrap3.py", line 438, in bootstrap_field
    return render_field(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\bootstrap3\forms.py", line 62, in render_field
    return renderer_cls(field, **kwargs).render()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\bootstrap3\renderers.py", line 215, in __init__
    'Parameter "field" should contain a valid Django BoundField.')
BootstrapError: Parameter "field" should contain a valid Django BoundField.
[11/Aug/2020 21:30:05] ERROR [django.request:256] Internal Server Error: /comprobantes/saldo_inicial/nuevo/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\base.py", line 1195, in render
    return func(*resolved_args, **resolved_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\bootstrap3\templatetags\bootstrap3.py", line 438, in bootstrap_field
    return render_field(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\bootstrap3\forms.py", line 62, in render_field
    return renderer_cls(field, **kwargs).render()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\bootstrap3\renderers.py", line 215, in __init__
    'Parameter "field" should contain a valid Django BoundField.')
BootstrapError: Parameter "field" should contain a valid Django BoundField.
[11/Aug/2020 21:36:23] ERROR [django.request:256] Internal Server Error: /comprobantes/saldo_inicial/nuevo/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\comprobantes\views.py", line 2043, in dispatch
    return super(SaldoInicialCreateView, self).dispatch(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 215, in post
    return self.form_valid(form)
  File "D:\Repo\ironStable\comprobantes\views.py", line 2060, in form_valid
    nro = ultimoNro(27,self.object.pto_vta,self.object.letra)
AttributeError: 'cpb_comprobante_fp' object has no attribute 'pto_vta'
[11/Aug/2020 21:36:43] ERROR [django.request:256] Internal Server Error: /comprobantes/saldo_inicial/nuevo/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\comprobantes\views.py", line 2043, in dispatch
    return super(SaldoInicialCreateView, self).dispatch(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 215, in post
    return self.form_valid(form)
  File "D:\Repo\ironStable\comprobantes\views.py", line 2060, in form_valid
    nro = ultimoNro(27,self.object.pto_vta,self.object.letra)
AttributeError: 'cpb_comprobante_fp' object has no attribute 'pto_vta'
[11/Aug/2020 21:37:21] ERROR [django.request:256] Internal Server Error: /comprobantes/saldo_inicial/nuevo/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\comprobantes\views.py", line 2043, in dispatch
    return super(SaldoInicialCreateView, self).dispatch(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 215, in post
    return self.form_valid(form)
  File "D:\Repo\ironStable\comprobantes\views.py", line 2065, in form_valid
    self.object.cpb_comprobante = cpb.id
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\fields\related.py", line 629, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "1242L": "cpb_comprobante_fp.cpb_comprobante" must be a "cpb_comprobante" instance.
[13/Aug/2020 20:25:17] ERROR [django.request:256] Internal Server Error: /reportes/ver_cierre_diario/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Repo\ironStable\reportes\views.py", line 797, in ver_cierre_diario
    cpbs = cpb_comprobante_fp.objects.filter(cpb_comprobante__empresa=empresa,mdcp_fecha__gte=fdesde,mdcp_fecha__lte=fhasta)\
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1310, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1338, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1156, in build_filter
    value, lookups, used_joins = self.prepare_lookup_value(value, lookups, can_reuse, allow_joins)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 996, in prepare_lookup_value
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[13/Aug/2020 20:25:35] ERROR [django.request:256] Internal Server Error: /reportes/ver_cierre_diario/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Repo\ironStable\reportes\views.py", line 797, in ver_cierre_diario
    cpbs = cpb_comprobante_fp.objects.filter(cpb_comprobante__empresa=empresa,mdcp_fecha__gte=fdesde,mdcp_fecha__lte=fhasta)\
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1310, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1338, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1156, in build_filter
    value, lookups, used_joins = self.prepare_lookup_value(value, lookups, can_reuse, allow_joins)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 996, in prepare_lookup_value
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[13/Aug/2020 20:26:24] ERROR [django.request:256] Internal Server Error: /reportes/ver_cierre_diario/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Repo\ironStable\reportes\views.py", line 797, in ver_cierre_diario
    cpbs = cpb_comprobante_fp.objects.filter(cpb_comprobante__empresa=empresa,mdcp_fecha__gte=fdesde,mdcp_fecha__lte=fhasta)\
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1310, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1338, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1209, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1102, in build_lookup
    return final_lookup(lhs, rhs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\lookups.py", line 101, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\lookups.py", line 139, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\fields\__init__.py", line 1313, in get_prep_lookup
    return super(DateField, self).get_prep_lookup(lookup_type, value)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\fields\__init__.py", line 727, in get_prep_lookup
    return self.get_prep_value(value)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\fields\__init__.py", line 1317, in get_prep_value
    return self.to_python(value)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\fields\__init__.py", line 1287, in to_python
    params={'value': value},
ValidationError: [u"'13/08/2020' valor tiene un formato de fecha no v\xe1lida. Debe estar en formato AAAA-MM-DD."]
[13/Aug/2020 20:27:55] ERROR [django.request:256] Internal Server Error: /reportes/ver_cierre_diario/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Repo\ironStable\reportes\views.py", line 789, in ver_cierre_diario
    fdesde = Date(request.GET.get('fdesde', hoy()))
NameError: global name 'Date' is not defined
[13/Aug/2020 20:28:37] ERROR [django.request:256] Internal Server Error: /reportes/ver_cierre_diario/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Repo\ironStable\reportes\views.py", line 789, in ver_cierre_diario
    fdesde = datetime. strptime(request.GET.get('fdesde', hoy()))
TypeError: strptime() takes exactly 2 arguments (1 given)
[13/Aug/2020 20:29:13] ERROR [django.request:256] Internal Server Error: /reportes/ver_cierre_diario/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Repo\ironStable\reportes\views.py", line 803, in ver_cierre_diario
    cpbs_debe = cpbs.filter(cta_ingreso=cta)
NameError: global name 'cta' is not defined
[13/Aug/2020 20:29:35] ERROR [django.request:256] Internal Server Error: /reportes/ver_cierre_diario/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Repo\ironStable\reportes\views.py", line 810, in ver_cierre_diario
    return render_to_response("reportes/caja_diaria_total.html", variables)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\template\loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: reportes/caja_diaria_total.html
[14/ago./2020 19:13:48] ERROR [django.request:256] Internal Server Error: /reportes/ver_cierre_diario/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Repo\ironStable\reportes\views.py", line 803, in ver_cierre_diario
    cpbs_debe = cpbs.filter(cta_ingreso=cuenta)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1310, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1338, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1200, in build_filter
    lookups, value)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\fields\related.py", line 1745, in get_lookup_constraint
    lookup_class(target.get_col(alias, source), val), AND)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\lookups.py", line 101, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\lookups.py", line 139, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\fields\__init__.py", line 727, in get_prep_lookup
    return self.get_prep_value(value)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\fields\__init__.py", line 985, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
[14/ago./2020 19:14:00] ERROR [django.request:256] Internal Server Error: /reportes/ver_cierre_diario/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Repo\ironStable\reportes\views.py", line 803, in ver_cierre_diario
    cpbs_debe = cpbs.filter(cta_ingreso=cuenta)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1310, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1338, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\query.py", line 1200, in build_filter
    lookups, value)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\fields\related.py", line 1745, in get_lookup_constraint
    lookup_class(target.get_col(alias, source), val), AND)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\lookups.py", line 101, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\lookups.py", line 139, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\fields\__init__.py", line 727, in get_prep_lookup
    return self.get_prep_value(value)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\fields\__init__.py", line 985, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
[26/Aug/2020 20:28:21] ERROR [django.request:256] Internal Server Error: /productos/producto_editar/1438/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\productos\views.py", line 164, in dispatch
    return super(ProductosEditView, self).dispatch(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Repo\ironStable\productos\views.py", line 181, in get
    form = self.get_form(form_class)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
  File "D:\Repo\ironStable\productos\forms.py", line 53, in __init__
    empresa = empresa_actual(request)
  File "D:\Repo\ironStable\general\utilidades.py", line 301, in empresa_actual
    return request.user.userprofile.id_usuario.empresa
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\fields\related.py", line 604, in __get__
    rel_obj = qs.get()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 328, in get
    num = len(clone)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 144, in __len__
    self._fetch_all()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\models\sql\compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\db\backends\mysql\base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\MySQLdb\cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\MySQLdb\connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (1054, "Unknown column 'gral_empresa.impuesto1' in 'field list'")
[26/Aug/2020 20:33:14] ERROR [django.request:256] Internal Server Error: /productos/prod_precios_editar/1823/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\productos\views.py", line 607, in dispatch
    return super(ProdLPreciosEditView, self).dispatch(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 268, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 205, in get
    form = self.get_form()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
  File "D:\Repo\ironStable\productos\forms.py", line 222, in __init__
    empresa = empresa_actual(request)
  File "D:\Repo\ironStable\general\utilidades.py", line 301, in empresa_actual
    return request.user.userprofile.id_usuario.empresa
AttributeError: 'NoneType' object has no attribute 'user'
[26/Aug/2020 20:33:42] ERROR [django.request:256] Internal Server Error: /productos/prod_precios_editar/1823/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\productos\views.py", line 607, in dispatch
    return super(ProdLPreciosEditView, self).dispatch(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 268, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 205, in get
    form = self.get_form()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
  File "D:\Repo\ironStable\productos\forms.py", line 222, in __init__
    empresa = empresa_actual(request)
  File "D:\Repo\ironStable\general\utilidades.py", line 301, in empresa_actual
    return request.user.userprofile.id_usuario.empresa
AttributeError: 'NoneType' object has no attribute 'user'
[26/Aug/2020 20:34:52] ERROR [django.request:256] Internal Server Error: /productos/prod_precios_editar/1823/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\productos\views.py", line 607, in dispatch
    return super(ProdLPreciosEditView, self).dispatch(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 268, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 205, in get
    form = self.get_form()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
  File "D:\Repo\ironStable\productos\forms.py", line 222, in __init__
    empresa = empresa_actual(request)
  File "D:\Repo\ironStable\general\utilidades.py", line 301, in empresa_actual
    return request.user.userprofile.id_usuario.empresa
AttributeError: 'NoneType' object has no attribute 'user'
[26/Aug/2020 20:36:53] ERROR [django.request:256] Internal Server Error: /productos/prod_precios_editar/1823/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\productos\views.py", line 607, in dispatch
    return super(ProdLPreciosEditView, self).dispatch(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 268, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 205, in get
    form = self.get_form()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
  File "D:\Repo\ironStable\productos\forms.py", line 222, in __init__
    empresa = empresa_actual(request)
  File "D:\Repo\ironStable\general\utilidades.py", line 301, in empresa_actual
    return request.user.userprofile.id_usuario.empresa
AttributeError: 'NoneType' object has no attribute 'user'
[26/Aug/2020 20:37:11] ERROR [django.request:256] Internal Server Error: /productos/prod_precios_editar/1823/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\productos\views.py", line 607, in dispatch
    return super(ProdLPreciosEditView, self).dispatch(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 268, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 205, in get
    form = self.get_form()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
  File "D:\Repo\ironStable\productos\forms.py", line 222, in __init__
    empresa = empresa_actual(request)
  File "D:\Repo\ironStable\general\utilidades.py", line 301, in empresa_actual
    return request.user.userprofile.id_usuario.empresa
AttributeError: 'NoneType' object has no attribute 'user'
[26/Aug/2020 20:40:43] ERROR [django.request:256] Internal Server Error: /productos/prod_precios_editar/1823/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\productos\views.py", line 607, in dispatch
    return super(ProdLPreciosEditView, self).dispatch(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 268, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 205, in get
    form = self.get_form()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
  File "D:\Repo\ironStable\productos\forms.py", line 222, in __init__
    empresa = empresa_actual(request)
  File "D:\Repo\ironStable\general\utilidades.py", line 301, in empresa_actual
    return request.user.userprofile.id_usuario.empresa
AttributeError: 'NoneType' object has no attribute 'user'
[26/Aug/2020 20:47:01] ERROR [django.request:256] Internal Server Error: /productos/prod_precios_editar/1823/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\productos\views.py", line 607, in dispatch
    return super(ProdLPreciosEditView, self).dispatch(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 268, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 205, in get
    form = self.get_form()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
  File "D:\Repo\ironStable\productos\forms.py", line 224, in __init__
    self.fields['precio_itc'].label = empresa.nombre_impuesto1
AttributeError: 'gral_empresa' object has no attribute 'nombre_impuesto1'
[26/Aug/2020 20:47:10] ERROR [django.request:256] Internal Server Error: /productos/prod_precios_editar/1823/
Traceback (most recent call last):
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\Repo\ironStable\productos\views.py", line 607, in dispatch
    return super(ProdLPreciosEditView, self).dispatch(*args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 268, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 205, in get
    form = self.get_form()
  File "C:\Users\juanma\Envs\ironstable\lib\site-packages\django\views\generic\edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
  File "D:\Repo\ironStable\productos\forms.py", line 224, in __init__
    self.fields['precio_itc'].label = empresa.nombre_impuesto1
AttributeError: 'gral_empresa' object has no attribute 'nombre_impuesto1'
